export const Colors = {
  primary: '#4840EE',
  primaryContainer: '#EEE9FE',
  accent: '#F58A07',
  surface: '#FFFFFF',
  surfaceSecondary: '#FAFAFA',
  surfaceTetriary: '#F5F5F5',
  surfaceInverse: '#000000',
  surfaceInverseSecondary: '#212121',
  surfaceInverseTetriary: '#424242',
  textPrimary: '#212121',
  textSecondary: '#616161',
  textTetriary: '#9E9E9E',
  textInversePrimary: '#FFFFFF',
  textInverseSecondary: '#FAFAFA',
  textInverseTetriary: '#F5F5F5',
  grey: {
    dark: '#9E9E9E',
    medium: '#BDBDBD',
    light: '#E0E0E0',
  },
  success: '#00A520',
  successContainer: '#E5F6E6',
  warning: '#E6353D',
  warningContainer: '#FEEBEF',
  alert: '#FFB201',
  alertContainer: '#FFF8E1',
  information: '#064FF3',
  informationContainer: '#E9ECFF',
};
